### ISSUE TITLE
Repo link of Api

### ISSUE THREAD

**Issue by skgupta507** [ooexiaoo/Miyou#1]
Hey @debsishu @Jeydin @ooexiaoo can u pls send me the link of the Repo of the Api which u have hosted cause the current Api link dosent seem to work.

**Comment by jeydinpham** [comment]
> Hey @debsishu @Jeydin @ooexiaoo can u pls send me the link of the Repo of the Api which u have hosted cause the current Api link dosent seem to work.

The API repository was made private by the maintainer, only the frontend was made public and if any copies were kept, they are probably outdated by now

**Comment by skgupta507** [comment]
> > Hey @debsishu @Jeydin @ooexiaoo can u pls send me the link of the Repo of the Api which u have hosted cause the current Api link dosent seem to work.
> 
> The API repository was made private by the maintainer, only the frontend was made public and if any copies were kept, they are probably outdated by now

Hey @Jeydin21 can u share the outdated code with me

**Comment by skgupta507** [comment]
Or if u can just point me to the right repo
Just what api is it using like gogoanime api Or anify api Or aniwatch api. 
I hosted the site 5months ago n iam still looking for a way to make the site work. 
So if u can share some details it would be much appreciated.

**Comment by ghost** [comment]
> > > Hey @debsishu @Jeydin @ooexiaoo can u pls send me the link of the Repo of the Api which u have hosted cause the current Api link dosent seem to work.
> 
> > 
> 
> > The API repository was made private by the maintainer, only the frontend was made public and if any copies were kept, they are probably outdated by now
> 
> 
> 
> Hey @Jeydin21 can u share the outdated code with me

I don't have a copy of it anymore, sorry

**Comment by ghost** [comment]
> Or if u can just point me to the right repo
> 
> Just what api is it using like gogoanime api Or anify api Or aniwatch api. 
> 
> I hosted the site 5months ago n iam still looking for a way to make the site work. 
> 
> So if u can share some details it would be much appreciated. 

I think it was their own API that they made

**Comment by ooexiaoo** [comment]
As Jeydin said, I think they were using their API, but don't have access to it as it must be stored in their .env folder.
BTW you can use [Miruro](https://github.com/Miruro-no-kuon/Miruro) for creating a different project and use [Consumet](https://github.com/consumet) for making your own API. I didn't look much into it, but might be helpful. You can look for more info on their pages. 👍🏻

**Comment by skgupta507** [comment]
> As Jeydin said, I think they were using their API, but don't have access to it as it must be stored in their .env folder. BTW you can use [Miruro](https://github.com/Miruro-no-kuon/Miruro) for creating a different project and use [Consumet](https://github.com/consumet) for making your own API. I didn't look much into it, but might be helpful. You can look for more info on their pages. 👍🏻

Hey @Jeydin @ooexiaoo thanks for answering my query and replying to my questions. 

Btw @ooexiaoo ru not the author of this repo

**Comment by ooexiaoo** [comment]
> Btw @ooexiaoo ru not the author of this repo

Yes but, no, I had forked this a few months ago to learn a few things, then never looked at it 😄

**Comment by skgupta507** [comment]
> > Btw @ooexiaoo ru not the author of this repo
> 
> Yes but, no, I had forked this a few months ago to learn a few things, then never looked at it 😄

Oh! ok
